sota_sanity.bbclass: don't use copy_data()
* fixes:
  https://github.com/uptane/meta-updater/issues/60

  meta-updater/classes/sota_sanity.bbclass", line 100, in defaultsota_check_sanity_eventhandler(e=<bb.event.SanityCheck object at 0x7fa32faedf30>):
           if bb.event.getName(e) == "SanityCheck":
      >        sanity_data = copy_data(e)
               if e.generateevents:
  NameError: name 'copy_data' is not defined

  copy_data function was removed in:
  https://git.openembedded.org/openembedded-core/commit/?id=d3eb4531aae28a07cb7e52ed5fe1102445d2effd

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>